export interface DefWord {
  id: string;
  word: string;
  definition: string;
  difficulty: 'easy' | 'medium' | 'hard' | 'expert' | 'master';
}

export const DEF_WORDS: DefWord[] = [
  // === EASY — Common everyday words ===
  { id: 'e1', word: 'bonheur', definition: 'État de satisfaction complète et durable.', difficulty: 'easy' },
  { id: 'e2', word: 'jardin', definition: 'Terrain où l\'on cultive des plantes, des fleurs ou des légumes.', difficulty: 'easy' },
  { id: 'e3', word: 'sourire', definition: 'Expression du visage qui marque la joie ou la sympathie.', difficulty: 'easy' },
  { id: 'e4', word: 'voyage', definition: 'Déplacement vers un lieu éloigné.', difficulty: 'easy' },
  { id: 'e5', word: 'silence', definition: 'Absence totale de bruit ou de son.', difficulty: 'easy' },
  { id: 'e6', word: 'chanson', definition: 'Texte mis en musique, destiné à être chanté.', difficulty: 'easy' },
  { id: 'e7', word: 'courage', definition: 'Force morale qui permet d\'affronter le danger ou la difficulté.', difficulty: 'easy' },
  { id: 'e8', word: 'liberté', definition: 'État d\'une personne qui n\'est pas soumise à une contrainte.', difficulty: 'easy' },
  { id: 'e9', word: 'famille', definition: 'Ensemble des personnes liées par le sang ou l\'alliance.', difficulty: 'easy' },
  { id: 'e10', word: 'lumière', definition: 'Ce qui éclaire, rayonnement visible à l\'œil.', difficulty: 'easy' },
  { id: 'e11', word: 'amitié', definition: 'Sentiment d\'affection réciproque entre deux personnes.', difficulty: 'easy' },
  { id: 'e12', word: 'saison', definition: 'Chacune des quatre divisions de l\'année (printemps, été, automne, hiver).', difficulty: 'easy' },
  { id: 'e13', word: 'rivière', definition: 'Cours d\'eau naturel de moyenne importance.', difficulty: 'easy' },
  { id: 'e14', word: 'mystère', definition: 'Ce qui est inconnu, caché ou incompréhensible.', difficulty: 'easy' },
  { id: 'e15', word: 'paysage', definition: 'Vue d\'ensemble d\'une étendue de pays.', difficulty: 'easy' },
  { id: 'e16', word: 'étoile', definition: 'Astre lumineux visible dans le ciel nocturne.', difficulty: 'easy' },
  { id: 'e17', word: 'colère', definition: 'Émotion violente provoquée par un sentiment d\'injustice ou de frustration.', difficulty: 'easy' },
  { id: 'e18', word: 'nuage', definition: 'Amas de vapeur d\'eau en suspension dans l\'atmosphère.', difficulty: 'easy' },
  { id: 'e19', word: 'oiseau', definition: 'Animal vertébré à plumes, pourvu d\'ailes et d\'un bec.', difficulty: 'easy' },
  { id: 'e20', word: 'fenêtre', definition: 'Ouverture dans un mur pour laisser entrer la lumière et l\'air.', difficulty: 'easy' },
  { id: 'e21', word: 'forêt', definition: 'Vaste étendue de terrain couverte d\'arbres.', difficulty: 'easy' },
  { id: 'e22', word: 'marché', definition: 'Lieu public où l\'on vend et achète des marchandises.', difficulty: 'easy' },
  { id: 'e23', word: 'orage', definition: 'Perturbation atmosphérique accompagnée d\'éclairs, de tonnerre et de pluie.', difficulty: 'easy' },
  { id: 'e24', word: 'tristesse', definition: 'État de peine, de chagrin qui affecte le moral.', difficulty: 'easy' },
  { id: 'e25', word: 'promesse', definition: 'Engagement verbal ou écrit de faire ou de ne pas faire quelque chose.', difficulty: 'easy' },
  { id: 'e26', word: 'montagne', definition: 'Élévation naturelle du sol de grande hauteur.', difficulty: 'easy' },
  { id: 'e27', word: 'fontaine', definition: 'Construction d\'où l\'eau jaillit pour l\'usage public ou l\'ornement.', difficulty: 'easy' },
  { id: 'e28', word: 'chemin', definition: 'Voie de terre étroite pour aller d\'un lieu à un autre.', difficulty: 'easy' },
  { id: 'e29', word: 'récolte', definition: 'Action de recueillir les produits de la terre arrivés à maturité.', difficulty: 'easy' },
  { id: 'e30', word: 'village', definition: 'Petit groupement d\'habitations en milieu rural.', difficulty: 'easy' },
  { id: 'e31', word: 'chaleur', definition: 'Sensation produite par une température élevée.', difficulty: 'easy' },
  { id: 'e32', word: 'reflet', definition: 'Image renvoyée par une surface polie ou un miroir.', difficulty: 'easy' },
  { id: 'e33', word: 'parfum', definition: 'Odeur agréable et pénétrante d\'une substance.', difficulty: 'easy' },
  { id: 'e34', word: 'horizon', definition: 'Ligne circulaire où la terre et le ciel semblent se rejoindre.', difficulty: 'easy' },
  { id: 'e35', word: 'racine', definition: 'Partie d\'une plante qui s\'enfonce dans le sol pour la nourrir.', difficulty: 'easy' },
  { id: 'e36', word: 'refuge', definition: 'Lieu où l\'on se met à l\'abri d\'un danger.', difficulty: 'easy' },
  { id: 'e37', word: 'fierté', definition: 'Sentiment de satisfaction légitime de soi-même ou de ses proches.', difficulty: 'easy' },
  { id: 'e38', word: 'coquillage', definition: 'Enveloppe calcaire qui protège certains mollusques marins.', difficulty: 'easy' },
  { id: 'e39', word: 'tempête', definition: 'Violente perturbation météorologique avec des vents très forts.', difficulty: 'easy' },
  { id: 'e40', word: 'enfance', definition: 'Période de la vie humaine qui va de la naissance à l\'adolescence.', difficulty: 'easy' },
  { id: 'e41', word: 'voisin', definition: 'Personne qui habite à proximité immédiate.', difficulty: 'easy' },
  { id: 'e42', word: 'bougie', definition: 'Bâtonnet de cire muni d\'une mèche que l\'on fait brûler pour éclairer.', difficulty: 'easy' },

  // === MEDIUM — Standard vocabulary ===
  { id: 'm1', word: 'nostalgie', definition: 'Regret mélancolique d\'un passé révolu ou d\'un lieu quitté.', difficulty: 'medium' },
  { id: 'm2', word: 'éloquence', definition: 'Art de bien parler, de convaincre par la parole.', difficulty: 'medium' },
  { id: 'm3', word: 'harmonie', definition: 'Accord agréable entre les parties d\'un ensemble.', difficulty: 'medium' },
  { id: 'm4', word: 'paradoxe', definition: 'Affirmation qui contredit l\'opinion commune ou la logique apparente.', difficulty: 'medium' },
  { id: 'm5', word: 'ambiguïté', definition: 'Caractère de ce qui peut être interprété de plusieurs façons.', difficulty: 'medium' },
  { id: 'm6', word: 'crépuscule', definition: 'Lumière faible qui suit le coucher du soleil.', difficulty: 'medium' },
  { id: 'm7', word: 'mélancolie', definition: 'Tristesse vague et profonde, sans cause précise.', difficulty: 'medium' },
  { id: 'm8', word: 'euphorie', definition: 'Sentiment intense de bien-être et d\'optimisme.', difficulty: 'medium' },
  { id: 'm9', word: 'réticence', definition: 'Hésitation à dire ou faire quelque chose.', difficulty: 'medium' },
  { id: 'm10', word: 'audace', definition: 'Disposition à entreprendre des actions hardies.', difficulty: 'medium' },
  { id: 'm11', word: 'empathie', definition: 'Capacité à ressentir les émotions d\'autrui.', difficulty: 'medium' },
  { id: 'm12', word: 'dilemme', definition: 'Obligation de choisir entre deux options également insatisfaisantes.', difficulty: 'medium' },
  { id: 'm13', word: 'sérénité', definition: 'État de calme et de tranquillité profonde.', difficulty: 'medium' },
  { id: 'm14', word: 'allégorie', definition: 'Représentation d\'une idée abstraite par une image concrète.', difficulty: 'medium' },
  { id: 'm15', word: 'cynisme', definition: 'Attitude de mépris envers les conventions morales.', difficulty: 'medium' },
  { id: 'm16', word: 'altruisme', definition: 'Disposition à se dévouer pour autrui sans rien attendre en retour.', difficulty: 'medium' },
  { id: 'm17', word: 'pragmatisme', definition: 'Attitude qui privilégie l\'action concrète et l\'efficacité pratique.', difficulty: 'medium' },
  { id: 'm18', word: 'réminiscence', definition: 'Souvenir vague et imprécis qui revient à la mémoire.', difficulty: 'medium' },
  { id: 'm19', word: 'désinvolture', definition: 'Attitude de légèreté et d\'aisance qui marque un manque de sérieux.', difficulty: 'medium' },
  { id: 'm20', word: 'quiétude', definition: 'État de calme paisible, absence d\'agitation ou d\'inquiétude.', difficulty: 'medium' },
  { id: 'm21', word: 'prémisse', definition: 'Proposition à partir de laquelle on tire une conclusion logique.', difficulty: 'medium' },
  { id: 'm22', word: 'subterfuge', definition: 'Moyen habile et détourné pour se tirer d\'embarras.', difficulty: 'medium' },
  { id: 'm23', word: 'préjugé', definition: 'Opinion adoptée sans examen, fondée sur des idées reçues.', difficulty: 'medium' },
  { id: 'm24', word: 'opiniâtreté', definition: 'Attachement obstiné et tenace à ses idées ou ses projets.', difficulty: 'medium' },
  { id: 'm25', word: 'réciprocité', definition: 'Caractère de ce qui est mutuel, échangé dans les deux sens.', difficulty: 'medium' },
  { id: 'm26', word: 'versatile', definition: 'Qui change facilement d\'opinion ou de parti.', difficulty: 'medium' },
  { id: 'm27', word: 'concession', definition: 'Abandon partiel d\'une position pour parvenir à un accord.', difficulty: 'medium' },
  { id: 'm28', word: 'prodige', definition: 'Événement extraordinaire qui semble surnaturel ou merveilleux.', difficulty: 'medium' },
  { id: 'm29', word: 'dérision', definition: 'Moquerie méprisante qui tourne en ridicule.', difficulty: 'medium' },
  { id: 'm30', word: 'éphémère', definition: 'Qui ne dure qu\'un temps très court.', difficulty: 'medium' },
  { id: 'm31', word: 'nonchalance', definition: 'Manque d\'ardeur, de vivacité dans les gestes ou le comportement.', difficulty: 'medium' },
  { id: 'm32', word: 'aversion', definition: 'Répugnance très vive envers une personne ou une chose.', difficulty: 'medium' },
  { id: 'm33', word: 'intégrité', definition: 'Qualité d\'une personne honnête et incorruptible.', difficulty: 'medium' },
  { id: 'm34', word: 'consensus', definition: 'Accord général entre les membres d\'un groupe.', difficulty: 'medium' },
  { id: 'm35', word: 'apathie', definition: 'Absence d\'énergie et d\'intérêt pour toute chose.', difficulty: 'medium' },
  { id: 'm36', word: 'élégance', definition: 'Qualité de ce qui est raffiné dans la forme ou les manières.', difficulty: 'medium' },
  { id: 'm37', word: 'indulgence', definition: 'Disposition à pardonner facilement les fautes d\'autrui.', difficulty: 'medium' },
  { id: 'm38', word: 'véracité', definition: 'Qualité de ce qui est conforme à la vérité.', difficulty: 'medium' },
  { id: 'm39', word: 'insolence', definition: 'Manque de respect audacieux et provocant envers autrui.', difficulty: 'medium' },
  { id: 'm40', word: 'frugalité', definition: 'Habitude de se contenter d\'une nourriture simple et peu abondante.', difficulty: 'medium' },
  { id: 'm41', word: 'contingence', definition: 'Caractère de ce qui peut se produire ou non, sans nécessité.', difficulty: 'medium' },
  { id: 'm42', word: 'suspicion', definition: 'Sentiment de méfiance fondé sur des indices vagues.', difficulty: 'medium' },

  // === HARD — Literary/cultivated words ===
  { id: 'h1', word: 'résilience', definition: 'Capacité à surmonter les épreuves et à se reconstruire.', difficulty: 'hard' },
  { id: 'h2', word: 'mansuétude', definition: 'Disposition d\'esprit qui porte à l\'indulgence et à la douceur.', difficulty: 'hard' },
  { id: 'h3', word: 'acrimonie', definition: 'Aigreur et âpreté dans le caractère ou les propos.', difficulty: 'hard' },
  { id: 'h4', word: 'pléthorique', definition: 'Qui est en excès, surabondant.', difficulty: 'hard' },
  { id: 'h5', word: 'laconique', definition: 'Qui s\'exprime en peu de mots.', difficulty: 'hard' },
  { id: 'h6', word: 'obséquieux', definition: 'Qui manifeste une politesse excessive par servilité.', difficulty: 'hard' },
  { id: 'h7', word: 'véhémence', definition: 'Force impétueuse dans l\'expression des sentiments.', difficulty: 'hard' },
  { id: 'h8', word: 'abnégation', definition: 'Sacrifice volontaire de soi-même au profit d\'autrui.', difficulty: 'hard' },
  { id: 'h9', word: 'irrévocable', definition: 'Qui ne peut être annulé ni modifié.', difficulty: 'hard' },
  { id: 'h10', word: 'délétère', definition: 'Qui met la santé ou la vie en danger, nuisible.', difficulty: 'hard' },
  { id: 'h11', word: 'pusillanime', definition: 'Qui manque de courage et de détermination.', difficulty: 'hard' },
  { id: 'h12', word: 'péremptoirement', definition: 'De manière qui n\'admet aucune discussion.', difficulty: 'hard' },
  { id: 'h13', word: 'ubiquité', definition: 'Capacité d\'être présent partout à la fois.', difficulty: 'hard' },
  { id: 'h14', word: 'incurie', definition: 'Négligence grave dans l\'exercice d\'une fonction.', difficulty: 'hard' },
  { id: 'h15', word: 'apocryphe', definition: 'Dont l\'authenticité est douteuse ou contestée.', difficulty: 'hard' },
  { id: 'h16', word: 'perspicacité', definition: 'Qualité de celui qui perçoit ce qui échappe aux autres.', difficulty: 'hard' },
  { id: 'h17', word: 'prodigalité', definition: 'Tendance à dépenser avec excès et sans compter.', difficulty: 'hard' },
  { id: 'h18', word: 'magnanimité', definition: 'Grandeur d\'âme qui porte à la générosité et au pardon.', difficulty: 'hard' },
  { id: 'h19', word: 'conciliabule', definition: 'Conversation secrète entre quelques personnes, à voix basse.', difficulty: 'hard' },
  { id: 'h20', word: 'truculent', definition: 'Qui exprime les choses avec une verve haute en couleur et réaliste.', difficulty: 'hard' },
  { id: 'h21', word: 'inanité', definition: 'Caractère de ce qui est vide de sens ou totalement inutile.', difficulty: 'hard' },
  { id: 'h22', word: 'componction', definition: 'Air de gravité affectée et de recueillement exagéré.', difficulty: 'hard' },
  { id: 'h23', word: 'impavide', definition: 'Qui ne manifeste aucune peur face au danger.', difficulty: 'hard' },
  { id: 'h24', word: 'flagornerie', definition: 'Flatterie basse et intéressée destinée à obtenir des faveurs.', difficulty: 'hard' },
  { id: 'h25', word: 'opprobre', definition: 'Honte publique et infamante liée à une action honteuse.', difficulty: 'hard' },
  { id: 'h26', word: 'comminatoire', definition: 'Qui contient une menace de sanction ou de châtiment.', difficulty: 'hard' },
  { id: 'h27', word: 'concupiscent', definition: 'Qui éprouve un fort penchant pour les plaisirs des sens.', difficulty: 'hard' },
  { id: 'h28', word: 'dithyrambique', definition: 'Qui exprime un enthousiasme excessif et des louanges outrées.', difficulty: 'hard' },
  { id: 'h29', word: 'acerbe', definition: 'Qui est mordant et blessant dans ses propos ou sa critique.', difficulty: 'hard' },
  { id: 'h30', word: 'péremptoire', definition: 'Qui n\'admet ni objection ni réplique, tranchant.', difficulty: 'hard' },
  { id: 'h31', word: 'prévarication', definition: 'Manquement grave d\'un fonctionnaire aux devoirs de sa charge.', difficulty: 'hard' },
  { id: 'h32', word: 'vindicatif', definition: 'Qui est porté à la vengeance et au ressentiment durable.', difficulty: 'hard' },
  { id: 'h33', word: 'cupidité', definition: 'Désir immodéré de richesses et de biens matériels.', difficulty: 'hard' },
  { id: 'h34', word: 'affabilité', definition: 'Politesse bienveillante et avenante dans les manières.', difficulty: 'hard' },
  { id: 'h35', word: 'pusillanimité', definition: 'Manque de courage, de hardiesse devant le danger ou la difficulté.', difficulty: 'hard' },
  { id: 'h36', word: 'incommensurable', definition: 'Qui est si grand qu\'il ne peut être mesuré ou comparé.', difficulty: 'hard' },
  { id: 'h37', word: 'récalcitrant', definition: 'Qui résiste avec entêtement à l\'autorité ou aux ordres.', difficulty: 'hard' },
  { id: 'h38', word: 'sédition', definition: 'Révolte concertée contre l\'autorité établie.', difficulty: 'hard' },
  { id: 'h39', word: 'vitupérer', definition: 'Blâmer violemment et avec emportement.', difficulty: 'hard' },
  { id: 'h40', word: 'insidieux', definition: 'Qui cherche à nuire de manière sournoise et dissimulée.', difficulty: 'hard' },
  { id: 'h41', word: 'tergiverser', definition: 'Hésiter longuement en utilisant des détours pour éviter de se décider.', difficulty: 'hard' },
  { id: 'h42', word: 'ostracisme', definition: 'Exclusion d\'une personne d\'un groupe par hostilité collective.', difficulty: 'hard' },

  // === EXPERT — Rare words ===
  { id: 'x1', word: 'ataraxie', definition: 'Tranquillité absolue de l\'âme, absence de troubles.', difficulty: 'expert' },
  { id: 'x2', word: 'syncrétisme', definition: 'Fusion de doctrines ou de systèmes de pensée différents.', difficulty: 'expert' },
  { id: 'x3', word: 'sérendipité', definition: 'Découverte heureuse faite par hasard.', difficulty: 'expert' },
  { id: 'x4', word: 'palimpseste', definition: 'Manuscrit dont le texte a été effacé pour y écrire de nouveau.', difficulty: 'expert' },
  { id: 'x5', word: 'thuriféraire', definition: 'Personne qui prodigue des éloges excessifs, flatteur.', difficulty: 'expert' },
  { id: 'x6', word: 'solipsisme', definition: 'Théorie selon laquelle seul le sujet pensant existe avec certitude.', difficulty: 'expert' },
  { id: 'x7', word: 'antinomie', definition: 'Contradiction entre deux lois ou deux principes.', difficulty: 'expert' },
  { id: 'x8', word: 'aporie', definition: 'Difficulté logique insoluble, impasse du raisonnement.', difficulty: 'expert' },
  { id: 'x9', word: 'concupiscence', definition: 'Penchant pour les plaisirs sensuels et les biens matériels.', difficulty: 'expert' },
  { id: 'x10', word: 'idiosyncrasie', definition: 'Tempérament particulier propre à chaque individu.', difficulty: 'expert' },
  { id: 'x11', word: 'prolepse', definition: 'Figure consistant à réfuter par avance une objection.', difficulty: 'expert' },
  { id: 'x12', word: 'velléité', definition: 'Volonté faible et passagère, intention sans suite.', difficulty: 'expert' },
  { id: 'x13', word: 'histrionique', definition: 'Qui cherche à attirer l\'attention de manière théâtrale.', difficulty: 'expert' },
  { id: 'x14', word: 'panégyrique', definition: 'Discours à la louange d\'une personne ou d\'une institution.', difficulty: 'expert' },
  { id: 'x15', word: 'épistémologie', definition: 'Étude critique des sciences et de la connaissance.', difficulty: 'expert' },
  { id: 'x16', word: 'atrabilaire', definition: 'D\'humeur sombre et colérique, enclin à l\'irritation.', difficulty: 'expert' },
  { id: 'x17', word: 'casuistique', definition: 'Méthode qui résout les cas de conscience par des distinctions subtiles.', difficulty: 'expert' },
  { id: 'x18', word: 'ontologie', definition: 'Partie de la philosophie qui étudie l\'être en tant qu\'être.', difficulty: 'expert' },
  { id: 'x19', word: 'anagogie', definition: 'Interprétation mystique d\'un texte qui élève l\'esprit vers le divin.', difficulty: 'expert' },
  { id: 'x20', word: 'circumlocution', definition: 'Manière détournée d\'exprimer une pensée en utilisant trop de mots.', difficulty: 'expert' },
  { id: 'x21', word: 'ergotage', definition: 'Manie de discuter sur des détails insignifiants et de chicaner.', difficulty: 'expert' },
  { id: 'x22', word: 'apothéose', definition: 'Point culminant d\'une action, glorification suprême.', difficulty: 'expert' },
  { id: 'x23', word: 'heuristique', definition: 'Méthode de recherche qui procède par tâtonnements et approximations successives.', difficulty: 'expert' },
  { id: 'x24', word: 'prosélytisme', definition: 'Zèle déployé pour convertir autrui à ses idées ou sa foi.', difficulty: 'expert' },
  { id: 'x25', word: 'anfractuosité', definition: 'Cavité irrégulière et profonde dans une roche ou une surface.', difficulty: 'expert' },
  { id: 'x26', word: 'sapience', definition: 'Sagesse profonde acquise par l\'expérience et la réflexion.', difficulty: 'expert' },
  { id: 'x27', word: 'inextricable', definition: 'Qui est si embrouillé qu\'on ne peut le démêler.', difficulty: 'expert' },
  { id: 'x28', word: 'lénifier', definition: 'Adoucir, calmer une douleur ou une tension.', difficulty: 'expert' },
  { id: 'x29', word: 'émollient', definition: 'Qui a la propriété d\'amollir et de détendre les tissus.', difficulty: 'expert' },
  { id: 'x30', word: 'obédience', definition: 'Soumission à une autorité religieuse ou idéologique.', difficulty: 'expert' },
  { id: 'x31', word: 'olographe', definition: 'Se dit d\'un testament entièrement écrit de la main du testateur.', difficulty: 'expert' },
  { id: 'x32', word: 'irénisme', definition: 'Attitude de conciliation qui cherche la paix entre doctrines opposées.', difficulty: 'expert' },
  { id: 'x33', word: 'métempsycose', definition: 'Croyance en la transmigration de l\'âme d\'un corps à un autre après la mort.', difficulty: 'expert' },
  { id: 'x34', word: 'sycophante', definition: 'Délateur, personne qui dénonce calomnieusement autrui.', difficulty: 'expert' },
  { id: 'x35', word: 'acmé', definition: 'Point culminant, moment où quelque chose atteint son intensité maximale.', difficulty: 'expert' },
  { id: 'x36', word: 'pleonasme', definition: 'Emploi simultané de termes ayant le même sens dans une expression.', difficulty: 'expert' },
  { id: 'x37', word: 'logorrhée', definition: 'Flux de paroles inutiles et intarissable.', difficulty: 'expert' },
  { id: 'x38', word: 'truchement', definition: 'Intermédiaire par lequel on s\'exprime ou on communique.', difficulty: 'expert' },
  { id: 'x39', word: 'rodomontade', definition: 'Fanfaronnade, vantardise ridicule d\'exploits imaginaires.', difficulty: 'expert' },
  { id: 'x40', word: 'cénacle', definition: 'Petit groupe de personnes partageant les mêmes idées ou goûts.', difficulty: 'expert' },

  // === MASTER — Obscure/specialized words ===
  { id: 'z1', word: 'apodictique', definition: 'Se dit d\'une proposition nécessairement vraie, indémontrable.', difficulty: 'master' },
  { id: 'z2', word: 'catachrèse', definition: 'Métaphore passée dans l\'usage courant (ex: "pied" d\'une table).', difficulty: 'master' },
  { id: 'z3', word: 'prétérition', definition: 'Figure de style qui consiste à dire qu\'on ne parlera pas de quelque chose tout en en parlant.', difficulty: 'master' },
  { id: 'z4', word: 'hypostasier', definition: 'Considérer une abstraction comme une réalité concrète.', difficulty: 'master' },
  { id: 'z5', word: 'étiologie', definition: 'Étude des causes et des origines d\'une maladie.', difficulty: 'master' },
  { id: 'z6', word: 'propédeutique', definition: 'Enseignement préparatoire à des études plus approfondies.', difficulty: 'master' },
  { id: 'z7', word: 'syllepse', definition: 'Figure de style qui utilise un mot à la fois au sens propre et au sens figuré.', difficulty: 'master' },
  { id: 'z8', word: 'stochastique', definition: 'Qui relève du calcul des probabilités et du hasard.', difficulty: 'master' },
  { id: 'z9', word: 'anamnèse', definition: 'Reconstitution de l\'historique médical d\'un patient par le souvenir.', difficulty: 'master' },
  { id: 'z10', word: 'paralogisme', definition: 'Raisonnement faux fait de bonne foi, sans intention de tromper.', difficulty: 'master' },
  { id: 'z11', word: 'apophatique', definition: 'Qui définit quelque chose par ce qu\'il n\'est pas.', difficulty: 'master' },
  { id: 'z12', word: 'herméneutique', definition: 'Art d\'interpréter les textes, notamment sacrés ou philosophiques.', difficulty: 'master' },
  { id: 'z13', word: 'axiologie', definition: 'Branche de la philosophie qui étudie les valeurs morales.', difficulty: 'master' },
  { id: 'z14', word: 'pérégrination', definition: 'Voyage long et aventureux à travers des terres lointaines.', difficulty: 'master' },
  { id: 'z15', word: 'synecdoque', definition: 'Figure de style qui désigne le tout par la partie ou inversement.', difficulty: 'master' },
  { id: 'z16', word: 'aporétique', definition: 'Qui relève d\'une impasse logique sans solution possible.', difficulty: 'master' },
  { id: 'z17', word: 'épiphanie', definition: 'Apparition soudaine d\'une vérité ou d\'une réalité essentielle.', difficulty: 'master' },
  { id: 'z18', word: 'chiasme', definition: 'Figure de style qui croise les termes de deux groupes syntaxiques.', difficulty: 'master' },
  { id: 'z19', word: 'nominalisme', definition: 'Doctrine philosophique selon laquelle les concepts généraux ne sont que des noms.', difficulty: 'master' },
  { id: 'z20', word: 'téléologie', definition: 'Doctrine qui explique les phénomènes par leurs causes finales ou leurs buts.', difficulty: 'master' },
  { id: 'z21', word: 'apophtegme', definition: 'Parole mémorable d\'un personnage illustre, sentence concise.', difficulty: 'master' },
  { id: 'z22', word: 'palilalie', definition: 'Trouble du langage caractérisé par la répétition involontaire de mots ou de syllabes.', difficulty: 'master' },
  { id: 'z23', word: 'éréthisme', definition: 'État d\'excitation excessive d\'un organe ou de l\'esprit.', difficulty: 'master' },
  { id: 'z24', word: 'enthymème', definition: 'Syllogisme abrégé dans lequel une des prémisses est sous-entendue.', difficulty: 'master' },
  { id: 'z25', word: 'gnose', definition: 'Connaissance ésotérique des mystères divins réservée aux initiés.', difficulty: 'master' },
  { id: 'z26', word: 'athanor', definition: 'Fourneau des alchimistes capable de maintenir une chaleur constante.', difficulty: 'master' },
  { id: 'z27', word: 'procrastination', definition: 'Tendance pathologique à remettre systématiquement au lendemain.', difficulty: 'master' },
  { id: 'z28', word: 'hapax', definition: 'Mot ou expression qui n\'est attesté qu\'une seule fois dans un corpus.', difficulty: 'master' },
  { id: 'z29', word: 'litote', definition: 'Figure de style qui dit moins pour faire entendre plus.', difficulty: 'master' },
  { id: 'z30', word: 'prosodie', definition: 'Ensemble des règles relatives au rythme, à l\'accentuation et à l\'intonation.', difficulty: 'master' },
  { id: 'z31', word: 'autarcie', definition: 'État d\'un pays ou d\'un individu qui se suffit à lui-même économiquement.', difficulty: 'master' },
  { id: 'z32', word: 'miasme', definition: 'Émanation malsaine provenant de matières en décomposition.', difficulty: 'master' },
  { id: 'z33', word: 'paréidolie', definition: 'Phénomène psychologique qui fait percevoir des formes familières dans des stimuli aléatoires.', difficulty: 'master' },
  { id: 'z34', word: 'aposiopèse', definition: 'Figure de style qui consiste à interrompre brusquement une phrase pour produire un effet.', difficulty: 'master' },
  { id: 'z35', word: 'exégèse', definition: 'Interprétation approfondie et méthodique d\'un texte sacré ou littéraire.', difficulty: 'master' },
  { id: 'z36', word: 'tautologie', definition: 'Proposition qui est vraie par sa seule forme logique, sans apporter d\'information.', difficulty: 'master' },
  { id: 'z37', word: 'épistaxis', definition: 'Saignement de nez d\'origine nasale.', difficulty: 'master' },
  { id: 'z38', word: 'noumène', definition: 'Réalité en soi, telle qu\'elle existe indépendamment de notre perception.', difficulty: 'master' },
  { id: 'z39', word: 'hendiadys', definition: 'Figure de style qui exprime une idée unique par deux mots coordonnés.', difficulty: 'master' },
  { id: 'z40', word: 'clinamen', definition: 'Déviation spontanée et imprévisible des atomes selon la philosophie épicurienne.', difficulty: 'master' },
];
