import type { GameConfig } from '@/types';
import type { TranslationKey } from '@/locales';

export const GAME_REGISTRY: GameConfig[] = [
  {
    id: 'speed-math',
    name: 'Calcul Express',
    description: 'Résous des opérations le plus vite possible !',
    icon: '🔢',
    skills: ['math', 'speed'],
    defaultDuration: 45,
    maxLevel: 5,
    color: '#3b82f6',
  },
  {
    id: 'memory-sequence',
    name: 'Suite Mémoire',
    description: 'Reproduis la séquence de cases illuminées.',
    icon: '🧠',
    skills: ['memory'],
    defaultDuration: 45,
    maxLevel: 5,
    color: '#8b5cf6',
  },
  {
    id: 'find-intruder',
    name: "Trouve l'intrus",
    description: "Trouve l'élément qui ne va pas dans la grille.",
    icon: '🔍',
    skills: ['attention', 'speed'],
    defaultDuration: 45,
    maxLevel: 5,
    color: '#06b6d4',
  },
  {
    id: 'reflex',
    name: 'Réflexe',
    description: 'Teste ta vitesse de réaction !',
    icon: '⚡',
    skills: ['speed', 'attention'],
    defaultDuration: 45,
    maxLevel: 5,
    color: '#f97316',
  },
  {
    id: 'logic-plus',
    name: 'Logique+',
    description: 'Complète les suites logiques.',
    icon: '🧩',
    skills: ['logic'],
    defaultDuration: 45,
    maxLevel: 5,
    color: '#10b981',
  },
  {
    id: 'right-word',
    name: 'Mot Juste',
    description: 'Trouve le bon mot : synonymes, antonymes, définitions.',
    icon: '📝',
    skills: ['language'],
    defaultDuration: 45,
    maxLevel: 5,
    color: '#ec4899',
  },
  {
    id: 'rotation',
    name: 'Rotation',
    description: 'Identifie la bonne rotation de la forme.',
    icon: '🔄',
    skills: ['logic', 'attention'],
    defaultDuration: 45,
    maxLevel: 5,
    color: '#10b981',
  },
  {
    id: 'search-count',
    name: 'Cherche & Compte',
    description: "Compte les éléments cibles parmi les distracteurs.",
    icon: '👁️',
    skills: ['attention'],
    defaultDuration: 45,
    maxLevel: 5,
    color: '#06b6d4',
  },
  {
    id: 'pairs',
    name: 'Paires',
    description: 'Retrouve les paires de cartes identiques.',
    icon: '🃏',
    skills: ['memory'],
    defaultDuration: 45,
    maxLevel: 5,
    color: '#8b5cf6',
  },
  {
    id: 'quick-sort',
    name: 'Tri Express',
    description: 'Remets les éléments dans le bon ordre.',
    icon: '📊',
    skills: ['logic', 'speed'],
    defaultDuration: 45,
    maxLevel: 5,
    color: '#f97316',
  },
  {
    id: 'trivia',
    name: 'Culture G',
    description: 'Teste ta culture générale sur plein de sujets !',
    icon: '🎓',
    skills: ['culture'],
    defaultDuration: 45,
    maxLevel: 5,
    color: '#a855f7',
  },
  {
    id: 'word-definition',
    name: 'Défini-Mot',
    description: 'Trouve le mot à partir de sa définition !',
    icon: '💬',
    skills: ['language'],
    defaultDuration: 45,
    maxLevel: 5,
    color: '#6366f1',
  },
];

export const GAME_MAP = new Map(GAME_REGISTRY.map((g) => [g.id, g]));

/** Maps game ID → translation keys for name and description */
export const GAME_I18N: Record<string, { name: TranslationKey; description: TranslationKey }> = {
  'speed-math': { name: 'game.speedMath.name', description: 'game.speedMath.description' },
  'memory-sequence': { name: 'game.memorySequence.name', description: 'game.memorySequence.description' },
  'find-intruder': { name: 'game.findIntruder.name', description: 'game.findIntruder.description' },
  'reflex': { name: 'game.reflex.name', description: 'game.reflex.description' },
  'logic-plus': { name: 'game.logicPlus.name', description: 'game.logicPlus.description' },
  'right-word': { name: 'game.rightWord.name', description: 'game.rightWord.description' },
  'rotation': { name: 'game.rotation.name', description: 'game.rotation.description' },
  'search-count': { name: 'game.searchCount.name', description: 'game.searchCount.description' },
  'pairs': { name: 'game.pairs.name', description: 'game.pairs.description' },
  'quick-sort': { name: 'game.quickSort.name', description: 'game.quickSort.description' },
  'trivia': { name: 'game.trivia.name', description: 'game.trivia.description' },
  'word-definition': { name: 'game.wordDefinition.name', description: 'game.wordDefinition.description' },
};
