import type { GameConfig } from '@/types';

export const GAME_REGISTRY: GameConfig[] = [
  {
    id: 'calcul-express',
    name: 'Calcul Express',
    description: 'Résous des opérations le plus vite possible !',
    icon: '🔢',
    skills: ['calcul', 'vitesse'],
    defaultDuration: 45,
    maxLevel: 5,
    color: '#3b82f6',
  },
  {
    id: 'suite-memoire',
    name: 'Suite Mémoire',
    description: 'Reproduis la séquence de cases illuminées.',
    icon: '🧠',
    skills: ['memoire'],
    defaultDuration: 45,
    maxLevel: 5,
    color: '#8b5cf6',
  },
  {
    id: 'trouve-intrus',
    name: "Trouve l'intrus",
    description: "Trouve l'élément qui ne va pas dans la grille.",
    icon: '🔍',
    skills: ['attention', 'vitesse'],
    defaultDuration: 45,
    maxLevel: 5,
    color: '#06b6d4',
  },
  {
    id: 'reflexe',
    name: 'Réflexe',
    description: 'Teste ta vitesse de réaction !',
    icon: '⚡',
    skills: ['vitesse', 'attention'],
    defaultDuration: 45,
    maxLevel: 5,
    color: '#f97316',
  },
  {
    id: 'logique-plus',
    name: 'Logique+',
    description: 'Complète les suites logiques.',
    icon: '🧩',
    skills: ['logique'],
    defaultDuration: 45,
    maxLevel: 5,
    color: '#10b981',
  },
  {
    id: 'mot-juste',
    name: 'Mot Juste',
    description: 'Trouve le bon mot : synonymes, antonymes, définitions.',
    icon: '📝',
    skills: ['langage'],
    defaultDuration: 45,
    maxLevel: 5,
    color: '#ec4899',
  },
  {
    id: 'rotation',
    name: 'Rotation',
    description: 'Identifie la bonne rotation de la forme.',
    icon: '🔄',
    skills: ['logique', 'attention'],
    defaultDuration: 45,
    maxLevel: 5,
    color: '#10b981',
  },
  {
    id: 'cherche-compte',
    name: 'Cherche & Compte',
    description: "Compte les éléments cibles parmi les distracteurs.",
    icon: '👁️',
    skills: ['attention'],
    defaultDuration: 45,
    maxLevel: 5,
    color: '#06b6d4',
  },
  {
    id: 'paires',
    name: 'Paires',
    description: 'Retrouve les paires de cartes identiques.',
    icon: '🃏',
    skills: ['memoire'],
    defaultDuration: 45,
    maxLevel: 5,
    color: '#8b5cf6',
  },
  {
    id: 'tri-express',
    name: 'Tri Express',
    description: 'Remets les éléments dans le bon ordre.',
    icon: '📊',
    skills: ['logique', 'vitesse'],
    defaultDuration: 45,
    maxLevel: 5,
    color: '#f97316',
  },
  {
    id: 'culture-g',
    name: 'Culture G',
    description: 'Teste ta culture générale sur plein de sujets !',
    icon: '🎓',
    skills: ['culture'],
    defaultDuration: 45,
    maxLevel: 5,
    color: '#a855f7',
  },
  {
    id: 'defini-mot',
    name: 'Défini-Mot',
    description: 'Trouve le mot à partir de sa définition !',
    icon: '💬',
    skills: ['langage'],
    defaultDuration: 45,
    maxLevel: 5,
    color: '#6366f1',
  },
];

export const GAME_MAP = new Map(GAME_REGISTRY.map((g) => [g.id, g]));
