export interface DefWord {
  id: string;
  word: string;
  definition: string;
  difficulty: 'easy' | 'medium' | 'hard' | 'expert' | 'master';
}

export const EN_DEF_WORDS: DefWord[] = [
  // === EASY — Common everyday words ===
  { id: 'en_e1', word: 'happiness', definition: 'A state of well-being and contentment.', difficulty: 'easy' },
  { id: 'en_e2', word: 'garden', definition: 'A piece of ground where flowers, vegetables, or herbs are cultivated.', difficulty: 'easy' },
  { id: 'en_e3', word: 'smile', definition: 'A facial expression showing pleasure or amusement, with upturned corners of the mouth.', difficulty: 'easy' },
  { id: 'en_e4', word: 'journey', definition: 'An act of traveling from one place to another, especially over a long distance.', difficulty: 'easy' },
  { id: 'en_e5', word: 'silence', definition: 'Complete absence of sound or noise.', difficulty: 'easy' },
  { id: 'en_e6', word: 'song', definition: 'A short piece of music with words that is meant to be sung.', difficulty: 'easy' },
  { id: 'en_e7', word: 'courage', definition: 'The ability to face danger or difficulty without fear.', difficulty: 'easy' },
  { id: 'en_e8', word: 'freedom', definition: 'The state of not being imprisoned or enslaved.', difficulty: 'easy' },
  { id: 'en_e9', word: 'family', definition: 'A group of people related by blood, marriage, or adoption.', difficulty: 'easy' },
  { id: 'en_e10', word: 'shadow', definition: 'A dark area produced by an object blocking light.', difficulty: 'easy' },
  { id: 'en_e11', word: 'friendship', definition: 'A bond of mutual affection between two people.', difficulty: 'easy' },
  { id: 'en_e12', word: 'storm', definition: 'A violent disturbance of the atmosphere with strong winds and usually rain or snow.', difficulty: 'easy' },
  { id: 'en_e13', word: 'river', definition: 'A large natural stream of water flowing to the sea or a lake.', difficulty: 'easy' },
  { id: 'en_e14', word: 'mystery', definition: 'Something that is difficult or impossible to understand or explain.', difficulty: 'easy' },
  { id: 'en_e15', word: 'landscape', definition: 'A wide view of the visible features of an area of land.', difficulty: 'easy' },
  { id: 'en_e16', word: 'candle', definition: 'A cylinder of wax with a central wick that is lit to produce light.', difficulty: 'easy' },
  { id: 'en_e17', word: 'anger', definition: 'A strong feeling of displeasure or hostility.', difficulty: 'easy' },
  { id: 'en_e18', word: 'treasure', definition: 'A quantity of precious metals, gems, or other valuable objects.', difficulty: 'easy' },

  // === MEDIUM — Standard vocabulary ===
  { id: 'en_m1', word: 'nostalgia', definition: 'A sentimental longing for the past or a former place.', difficulty: 'medium' },
  { id: 'en_m2', word: 'eloquence', definition: 'Fluent or persuasive speaking or writing.', difficulty: 'medium' },
  { id: 'en_m3', word: 'harmony', definition: 'A pleasing arrangement of parts forming a consistent whole.', difficulty: 'medium' },
  { id: 'en_m4', word: 'paradox', definition: 'A statement that contradicts itself but may contain a truth.', difficulty: 'medium' },
  { id: 'en_m5', word: 'ambiguity', definition: 'The quality of being open to more than one interpretation.', difficulty: 'medium' },
  { id: 'en_m6', word: 'twilight', definition: 'The soft glowing light from the sky after sunset and before sunrise.', difficulty: 'medium' },
  { id: 'en_m7', word: 'melancholy', definition: 'A deep, persistent sadness with no obvious cause.', difficulty: 'medium' },
  { id: 'en_m8', word: 'euphoria', definition: 'An intense feeling of well-being and excitement.', difficulty: 'medium' },
  { id: 'en_m9', word: 'empathy', definition: 'The ability to understand and share the feelings of another.', difficulty: 'medium' },
  { id: 'en_m10', word: 'dilemma', definition: 'A situation requiring a choice between two equally undesirable options.', difficulty: 'medium' },
  { id: 'en_m11', word: 'serenity', definition: 'The state of being calm, peaceful, and untroubled.', difficulty: 'medium' },
  { id: 'en_m12', word: 'allegory', definition: 'A story in which characters and events represent abstract ideas or moral qualities.', difficulty: 'medium' },
  { id: 'en_m13', word: 'cynicism', definition: 'An attitude of scornful distrust of human sincerity and motives.', difficulty: 'medium' },
  { id: 'en_m14', word: 'altruism', definition: 'Selfless concern for the well-being of others.', difficulty: 'medium' },
  { id: 'en_m15', word: 'pragmatism', definition: 'An approach that evaluates ideas based on their practical consequences.', difficulty: 'medium' },
  { id: 'en_m16', word: 'integrity', definition: 'The quality of being honest and having strong moral principles.', difficulty: 'medium' },
  { id: 'en_m17', word: 'consensus', definition: 'A general agreement among the members of a group.', difficulty: 'medium' },
  { id: 'en_m18', word: 'apathy', definition: 'Lack of interest, enthusiasm, or concern.', difficulty: 'medium' },

  // === HARD — Literary/cultivated words ===
  { id: 'en_h1', word: 'resilience', definition: 'The capacity to recover quickly from difficulties.', difficulty: 'hard' },
  { id: 'en_h2', word: 'epiphany', definition: 'A sudden realization or profound insight about the nature of something.', difficulty: 'hard' },
  { id: 'en_h3', word: 'acrimony', definition: 'Bitterness or ill feeling in speech or manner.', difficulty: 'hard' },
  { id: 'en_h4', word: 'magnanimity', definition: 'Generosity of spirit, especially toward a rival or less powerful person.', difficulty: 'hard' },
  { id: 'en_h5', word: 'laconic', definition: 'Using very few words to express oneself.', difficulty: 'hard' },
  { id: 'en_h6', word: 'vehemence', definition: 'Great forcefulness or intensity of feeling or expression.', difficulty: 'hard' },
  { id: 'en_h7', word: 'abnegation', definition: 'The act of renouncing or rejecting something, especially self-sacrifice.', difficulty: 'hard' },
  { id: 'en_h8', word: 'ubiquity', definition: 'The state of appearing to be present everywhere at once.', difficulty: 'hard' },
  { id: 'en_h9', word: 'perspicacity', definition: 'The quality of having keen mental perception and understanding.', difficulty: 'hard' },
  { id: 'en_h10', word: 'prodigality', definition: 'Reckless extravagance or wastefulness in spending.', difficulty: 'hard' },
  { id: 'en_h11', word: 'cupidity', definition: 'Excessive greed for wealth or possessions.', difficulty: 'hard' },
  { id: 'en_h12', word: 'opprobrium', definition: 'Harsh criticism or public disgrace arising from shameful conduct.', difficulty: 'hard' },
  { id: 'en_h13', word: 'ostracism', definition: 'Exclusion from a group or society by general consent.', difficulty: 'hard' },
  { id: 'en_h14', word: 'sycophant', definition: 'A person who acts obsequiously to gain advantage from someone powerful.', difficulty: 'hard' },
  { id: 'en_h15', word: 'recalcitrant', definition: 'Stubbornly resistant to authority or control.', difficulty: 'hard' },
  { id: 'en_h16', word: 'insidious', definition: 'Proceeding in a gradual, subtle way but with harmful effects.', difficulty: 'hard' },
  { id: 'en_h17', word: 'temerity', definition: 'Excessive confidence or boldness; audacity.', difficulty: 'hard' },
  { id: 'en_h18', word: 'equanimity', definition: 'Mental calmness and composure, especially in a difficult situation.', difficulty: 'hard' },

  // === EXPERT — Rare words ===
  { id: 'en_x1', word: 'ataraxia', definition: 'A state of serene calmness and freedom from emotional disturbance.', difficulty: 'expert' },
  { id: 'en_x2', word: 'syncretism', definition: 'The merging of different religions, cultures, or schools of thought.', difficulty: 'expert' },
  { id: 'en_x3', word: 'serendipity', definition: 'The occurrence of finding valuable things by happy accident.', difficulty: 'expert' },
  { id: 'en_x4', word: 'palimpsest', definition: 'A manuscript on which earlier writing has been erased to make room for new text.', difficulty: 'expert' },
  { id: 'en_x5', word: 'solipsism', definition: 'The philosophical idea that only one\'s own mind is sure to exist.', difficulty: 'expert' },
  { id: 'en_x6', word: 'antinomy', definition: 'A contradiction between two beliefs or conclusions that are both reasonable.', difficulty: 'expert' },
  { id: 'en_x7', word: 'idiosyncrasy', definition: 'A distinctive behavioral trait or peculiar habit of an individual.', difficulty: 'expert' },
  { id: 'en_x8', word: 'panegyric', definition: 'A public speech or written text praising someone or something highly.', difficulty: 'expert' },
  { id: 'en_x9', word: 'epistemology', definition: 'The branch of philosophy concerned with the nature and scope of knowledge.', difficulty: 'expert' },
  { id: 'en_x10', word: 'casuistry', definition: 'The use of clever but unsound reasoning to resolve moral dilemmas.', difficulty: 'expert' },
  { id: 'en_x11', word: 'ontology', definition: 'The branch of philosophy dealing with the nature of being and existence.', difficulty: 'expert' },
  { id: 'en_x12', word: 'heuristic', definition: 'A practical method of problem-solving that uses shortcuts to produce good-enough solutions.', difficulty: 'expert' },
  { id: 'en_x13', word: 'proselytism', definition: 'The practice of attempting to convert someone to a different religion or opinion.', difficulty: 'expert' },
  { id: 'en_x14', word: 'sapience', definition: 'Deep wisdom acquired through experience and reflection.', difficulty: 'expert' },
  { id: 'en_x15', word: 'metempsychosis', definition: 'The supposed transmigration of the soul from one body to another after death.', difficulty: 'expert' },
  { id: 'en_x16', word: 'logorrhoea', definition: 'An excessive and uncontrollable flow of words.', difficulty: 'expert' },
  { id: 'en_x17', word: 'verisimilitude', definition: 'The appearance of being true or real.', difficulty: 'expert' },
  { id: 'en_x18', word: 'pleonasm', definition: 'The use of more words than necessary to express an idea.', difficulty: 'expert' },

  // === MASTER — Obscure/specialized words ===
  { id: 'en_z1', word: 'apodictic', definition: 'Clearly established or beyond dispute; necessarily true.', difficulty: 'master' },
  { id: 'en_z2', word: 'catachresis', definition: 'The misuse of a word, or a strained metaphor accepted through common usage.', difficulty: 'master' },
  { id: 'en_z3', word: 'praeterition', definition: 'A rhetorical device of emphasizing something by claiming to pass over it.', difficulty: 'master' },
  { id: 'en_z4', word: 'hypostatize', definition: 'To treat an abstract concept as if it were a concrete reality.', difficulty: 'master' },
  { id: 'en_z5', word: 'etiology', definition: 'The study of the causes and origins of diseases.', difficulty: 'master' },
  { id: 'en_z6', word: 'propaedeutic', definition: 'An introductory course of study serving as preparation for more advanced learning.', difficulty: 'master' },
  { id: 'en_z7', word: 'stochastic', definition: 'Having a random probability distribution that can be analyzed statistically.', difficulty: 'master' },
  { id: 'en_z8', word: 'anamnesis', definition: 'The recollection of a patient\'s medical history from memory.', difficulty: 'master' },
  { id: 'en_z9', word: 'paralogism', definition: 'A piece of illogical reasoning made in good faith, without intent to deceive.', difficulty: 'master' },
  { id: 'en_z10', word: 'hermeneutics', definition: 'The theory and methodology of interpreting texts, especially sacred writings.', difficulty: 'master' },
  { id: 'en_z11', word: 'axiology', definition: 'The branch of philosophy dealing with the nature of values and value judgments.', difficulty: 'master' },
  { id: 'en_z12', word: 'synecdoche', definition: 'A figure of speech in which a part is used to represent the whole or vice versa.', difficulty: 'master' },
  { id: 'en_z13', word: 'chiasmus', definition: 'A rhetorical figure in which two clauses are related by reversing their structures.', difficulty: 'master' },
  { id: 'en_z14', word: 'teleology', definition: 'The doctrine that phenomena are best explained by their purposes rather than their causes.', difficulty: 'master' },
  { id: 'en_z15', word: 'apothegm', definition: 'A concise and memorable saying embodying an important truth.', difficulty: 'master' },
  { id: 'en_z16', word: 'noumenon', definition: 'A thing as it is in itself, independent of how it is perceived.', difficulty: 'master' },
  { id: 'en_z17', word: 'tmesis', definition: 'The separation of a word into two parts by inserting another word between them.', difficulty: 'master' },
  { id: 'en_z18', word: 'clinamen', definition: 'The spontaneous and unpredictable swerve of atoms in Epicurean philosophy.', difficulty: 'master' },
];
