export interface WordQuestion {
  word: string;
  type: 'synonym' | 'antonym' | 'definition';
  question: string;
  options: [string, string, string, string];
  correctIndex: number;
  difficulty: 'easy' | 'medium' | 'hard' | 'expert' | 'master';
}

export const WORD_QUESTIONS: WordQuestion[] = [
  // === EASY ===
  { word: 'content', type: 'synonym', question: 'Synonyme de "content"', options: ['Heureux', 'Triste', 'Fatigué', 'Calme'], correctIndex: 0, difficulty: 'easy' },
  { word: 'rapide', type: 'synonym', question: 'Synonyme de "rapide"', options: ['Lent', 'Vif', 'Lourd', 'Doux'], correctIndex: 1, difficulty: 'easy' },
  { word: 'grand', type: 'antonym', question: 'Antonyme de "grand"', options: ['Petit', 'Large', 'Haut', 'Fort'], correctIndex: 0, difficulty: 'easy' },
  { word: 'chaud', type: 'antonym', question: 'Antonyme de "chaud"', options: ['Tiède', 'Brûlant', 'Froid', 'Doux'], correctIndex: 2, difficulty: 'easy' },
  { word: 'beau', type: 'synonym', question: 'Synonyme de "beau"', options: ['Laid', 'Joli', 'Sombre', 'Rude'], correctIndex: 1, difficulty: 'easy' },
  { word: 'triste', type: 'antonym', question: 'Antonyme de "triste"', options: ['Morose', 'Morne', 'Joyeux', 'Pensif'], correctIndex: 2, difficulty: 'easy' },
  { word: 'commencer', type: 'synonym', question: 'Synonyme de "commencer"', options: ['Finir', 'Débuter', 'Arrêter', 'Couper'], correctIndex: 1, difficulty: 'easy' },
  { word: 'ancien', type: 'antonym', question: 'Antonyme de "ancien"', options: ['Vieux', 'Moderne', 'Usé', 'Classique'], correctIndex: 1, difficulty: 'easy' },
  { word: 'facile', type: 'antonym', question: 'Antonyme de "facile"', options: ['Simple', 'Aisé', 'Difficile', 'Clair'], correctIndex: 2, difficulty: 'easy' },
  { word: 'riche', type: 'antonym', question: 'Antonyme de "riche"', options: ['Pauvre', 'Aisé', 'Fortuné', 'Noble'], correctIndex: 0, difficulty: 'easy' },
  { word: 'courage', type: 'synonym', question: 'Synonyme de "courage"', options: ['Peur', 'Bravoure', 'Lâcheté', 'Doute'], correctIndex: 1, difficulty: 'easy' },
  { word: 'donner', type: 'antonym', question: 'Antonyme de "donner"', options: ['Offrir', 'Prendre', 'Partager', 'Céder'], correctIndex: 1, difficulty: 'easy' },
  { word: 'ami', type: 'antonym', question: 'Antonyme de "ami"', options: ['Camarade', 'Compagnon', 'Ennemi', 'Voisin'], correctIndex: 2, difficulty: 'easy' },
  { word: 'parler', type: 'synonym', question: 'Synonyme de "parler"', options: ['Écouter', 'Dire', 'Voir', 'Sentir'], correctIndex: 1, difficulty: 'easy' },
  { word: 'maison', type: 'synonym', question: 'Synonyme de "maison"', options: ['Demeure', 'Jardin', 'Route', 'Pont'], correctIndex: 0, difficulty: 'easy' },
  { word: 'fort', type: 'synonym', question: 'Synonyme de "fort"', options: ['Faible', 'Mince', 'Puissant', 'Léger'], correctIndex: 2, difficulty: 'easy' },
  { word: 'manger', type: 'synonym', question: 'Synonyme de "manger"', options: ['Boire', 'Dormir', 'Courir', 'Se nourrir'], correctIndex: 3, difficulty: 'easy' },
  { word: 'lent', type: 'antonym', question: 'Antonyme de "lent"', options: ['Rapide', 'Lourd', 'Mou', 'Calme'], correctIndex: 0, difficulty: 'easy' },
  { word: 'clair', type: 'antonym', question: 'Antonyme de "clair"', options: ['Lumineux', 'Brillant', 'Transparent', 'Sombre'], correctIndex: 3, difficulty: 'easy' },
  { word: 'peur', type: 'definition', question: 'Que signifie "peur" ?', options: ['Joie intense', 'Sentiment de danger', 'Envie de dormir', 'Colère sourde'], correctIndex: 1, difficulty: 'easy' },
  { word: 'gentil', type: 'antonym', question: 'Antonyme de "gentil"', options: ['Aimable', 'Poli', 'Méchant', 'Doux'], correctIndex: 2, difficulty: 'easy' },
  { word: 'fatigué', type: 'synonym', question: 'Synonyme de "fatigué"', options: ['Énergique', 'Vif', 'Alerte', 'Épuisé'], correctIndex: 3, difficulty: 'easy' },
  { word: 'acheter', type: 'antonym', question: 'Antonyme de "acheter"', options: ['Vendre', 'Payer', 'Offrir', 'Garder'], correctIndex: 0, difficulty: 'easy' },
  { word: 'erreur', type: 'definition', question: 'Que signifie "erreur" ?', options: ['Réussite', 'Progrès', 'Faute involontaire', 'Victoire'], correctIndex: 2, difficulty: 'easy' },
  { word: 'monter', type: 'antonym', question: 'Antonyme de "monter"', options: ['Grimper', 'Sauter', 'Voler', 'Descendre'], correctIndex: 3, difficulty: 'easy' },
  { word: 'joli', type: 'definition', question: 'Que signifie "joli" ?', options: ['Agréable à regarder', 'Très grand', 'Bruyant', 'Ennuyeux'], correctIndex: 0, difficulty: 'easy' },
  { word: 'rire', type: 'antonym', question: 'Antonyme de "rire"', options: ['Sourire', 'Pleurer', 'Chanter', 'Crier'], correctIndex: 1, difficulty: 'easy' },
  { word: 'chemin', type: 'definition', question: 'Que signifie "chemin" ?', options: ['Rivière', 'Montagne', 'Voie pour se déplacer', 'Forêt'], correctIndex: 2, difficulty: 'easy' },
  { word: 'terminer', type: 'synonym', question: 'Synonyme de "terminer"', options: ['Commencer', 'Ouvrir', 'Lancer', 'Achever'], correctIndex: 3, difficulty: 'easy' },

  // === MEDIUM ===
  { word: 'altruiste', type: 'definition', question: 'Que signifie "altruiste" ?', options: ['Égoïste', 'Généreux envers autrui', 'Courageux', 'Prudent'], correctIndex: 1, difficulty: 'medium' },
  { word: 'éphémère', type: 'synonym', question: 'Synonyme de "éphémère"', options: ['Éternel', 'Passager', 'Solide', 'Puissant'], correctIndex: 1, difficulty: 'medium' },
  { word: 'lucide', type: 'definition', question: 'Que signifie "lucide" ?', options: ['Confus', 'Clairvoyant', 'Endormi', 'Hésitant'], correctIndex: 1, difficulty: 'medium' },
  { word: 'pérenne', type: 'antonym', question: 'Antonyme de "pérenne"', options: ['Durable', 'Temporaire', 'Stable', 'Ancien'], correctIndex: 1, difficulty: 'medium' },
  { word: 'pragmatique', type: 'definition', question: 'Que signifie "pragmatique" ?', options: ['Rêveur', 'Orienté vers la pratique', 'Timide', 'Impulsif'], correctIndex: 1, difficulty: 'medium' },
  { word: 'véhément', type: 'synonym', question: 'Synonyme de "véhément"', options: ['Calme', 'Ardent', 'Timide', 'Doux'], correctIndex: 1, difficulty: 'medium' },
  { word: 'prolixe', type: 'definition', question: 'Que signifie "prolixe" ?', options: ['Bref', 'Qui parle beaucoup', 'Silencieux', 'Précis'], correctIndex: 1, difficulty: 'medium' },
  { word: 'tenace', type: 'synonym', question: 'Synonyme de "tenace"', options: ['Fragile', 'Persistant', 'Faible', 'Souple'], correctIndex: 1, difficulty: 'medium' },
  { word: 'austère', type: 'antonym', question: 'Antonyme de "austère"', options: ['Sévère', 'Fastueux', 'Strict', 'Rigide'], correctIndex: 1, difficulty: 'medium' },
  { word: 'concis', type: 'antonym', question: 'Antonyme de "concis"', options: ['Bref', 'Court', 'Verbeux', 'Précis'], correctIndex: 2, difficulty: 'medium' },
  { word: 'sagace', type: 'definition', question: 'Que signifie "sagace" ?', options: ['Étourdi', 'Fin et perspicace', 'Lent', 'Naïf'], correctIndex: 1, difficulty: 'medium' },
  { word: 'prodigue', type: 'definition', question: 'Que signifie "prodigue" ?', options: ['Avare', 'Qui dépense sans compter', 'Prudent', 'Modeste'], correctIndex: 1, difficulty: 'medium' },
  { word: 'stoïque', type: 'synonym', question: 'Synonyme de "stoïque"', options: ['Émotif', 'Impassible', 'Agité', 'Nerveux'], correctIndex: 1, difficulty: 'medium' },
  { word: 'ambigu', type: 'antonym', question: 'Antonyme de "ambigu"', options: ['Flou', 'Vague', 'Clair', 'Incertain'], correctIndex: 2, difficulty: 'medium' },
  { word: 'corroborer', type: 'synonym', question: 'Synonyme de "corroborer"', options: ['Contredire', 'Confirmer', 'Ignorer', 'Douter'], correctIndex: 1, difficulty: 'medium' },
  { word: 'assidu', type: 'definition', question: 'Que signifie "assidu" ?', options: ['Régulier et appliqué', 'Paresseux', 'Distrait', 'Indifférent'], correctIndex: 0, difficulty: 'medium' },
  { word: 'loquace', type: 'antonym', question: 'Antonyme de "loquace"', options: ['Bavard', 'Volubile', 'Taciturne', 'Expressif'], correctIndex: 2, difficulty: 'medium' },
  { word: 'parcimonie', type: 'definition', question: 'Que signifie "parcimonie" ?', options: ['Abondance', 'Générosité', 'Excès', 'Économie excessive'], correctIndex: 3, difficulty: 'medium' },
  { word: 'candide', type: 'synonym', question: 'Synonyme de "candide"', options: ['Naïf', 'Rusé', 'Méfiant', 'Sournois'], correctIndex: 0, difficulty: 'medium' },
  { word: 'opiniâtre', type: 'synonym', question: 'Synonyme de "opiniâtre"', options: ['Souple', 'Hésitant', 'Obstiné', 'Indécis'], correctIndex: 2, difficulty: 'medium' },
  { word: 'versatile', type: 'definition', question: 'Que signifie "versatile" ?', options: ['Stable', 'Fidèle', 'Constant', 'Changeant d\'avis'], correctIndex: 3, difficulty: 'medium' },
  { word: 'prépondérant', type: 'synonym', question: 'Synonyme de "prépondérant"', options: ['Dominant', 'Secondaire', 'Négligeable', 'Accessoire'], correctIndex: 0, difficulty: 'medium' },
  { word: 'exacerber', type: 'definition', question: 'Que signifie "exacerber" ?', options: ['Calmer', 'Aggraver intensément', 'Résoudre', 'Ignorer'], correctIndex: 1, difficulty: 'medium' },
  { word: 'flegmatique', type: 'antonym', question: 'Antonyme de "flegmatique"', options: ['Calme', 'Posé', 'Fougueux', 'Serein'], correctIndex: 2, difficulty: 'medium' },
  { word: 'irascible', type: 'definition', question: 'Que signifie "irascible" ?', options: ['Patient', 'Doux', 'Calme', 'Prompt à la colère'], correctIndex: 3, difficulty: 'medium' },
  { word: 'laïc', type: 'antonym', question: 'Antonyme de "laïc"', options: ['Religieux', 'Civil', 'Neutre', 'Séculier'], correctIndex: 0, difficulty: 'medium' },
  { word: 'notoire', type: 'synonym', question: 'Synonyme de "notoire"', options: ['Secret', 'Célèbre', 'Discret', 'Inconnu'], correctIndex: 1, difficulty: 'medium' },
  { word: 'réfuter', type: 'antonym', question: 'Antonyme de "réfuter"', options: ['Contester', 'Nier', 'Approuver', 'Démentir'], correctIndex: 2, difficulty: 'medium' },
  { word: 'sédentaire', type: 'antonym', question: 'Antonyme de "sédentaire"', options: ['Casanier', 'Immobile', 'Fixe', 'Nomade'], correctIndex: 3, difficulty: 'medium' },

  // === HARD ===
  { word: 'obséquieux', type: 'definition', question: 'Que signifie "obséquieux" ?', options: ['Insolent', 'Excessivement poli', 'Distrait', 'Courageux'], correctIndex: 1, difficulty: 'hard' },
  { word: 'acrimonie', type: 'synonym', question: 'Synonyme de "acrimonie"', options: ['Douceur', 'Aigreur', 'Bonté', 'Gaieté'], correctIndex: 1, difficulty: 'hard' },
  { word: 'pusillanime', type: 'definition', question: 'Que signifie "pusillanime" ?', options: ['Courageux', 'Qui manque de courage', 'Généreux', 'Ambitieux'], correctIndex: 1, difficulty: 'hard' },
  { word: 'apocryphe', type: 'definition', question: 'Que signifie "apocryphe" ?', options: ['Authentique', "D'authenticité douteuse", 'Ancien', 'Sacré'], correctIndex: 1, difficulty: 'hard' },
  { word: 'dirimant', type: 'definition', question: 'Que signifie "dirimant" ?', options: ['Qui annule', 'Qui confirme', 'Qui clarifie', 'Qui améliore'], correctIndex: 0, difficulty: 'hard' },
  { word: 'incurie', type: 'definition', question: 'Que signifie "incurie" ?', options: ['Compétence', 'Négligence', 'Curiosité', 'Soin'], correctIndex: 1, difficulty: 'hard' },
  { word: 'pléthorique', type: 'antonym', question: 'Antonyme de "pléthorique"', options: ['Abondant', 'Insuffisant', 'Excessif', 'Complet'], correctIndex: 1, difficulty: 'hard' },
  { word: 'laconique', type: 'synonym', question: 'Synonyme de "laconique"', options: ['Bavard', 'Bref', 'Explicite', 'Long'], correctIndex: 1, difficulty: 'hard' },
  { word: 'acerbe', type: 'synonym', question: 'Synonyme de "acerbe"', options: ['Doux', 'Caustique', 'Tendre', 'Aimable'], correctIndex: 1, difficulty: 'hard' },
  { word: 'délétère', type: 'definition', question: 'Que signifie "délétère" ?', options: ['Bénéfique', 'Nuisible', 'Neutre', 'Salutaire'], correctIndex: 1, difficulty: 'hard' },
  { word: 'mansuétude', type: 'definition', question: 'Que signifie "mansuétude" ?', options: ['Sévérité', 'Indulgence et douceur', 'Colère', 'Indifférence'], correctIndex: 1, difficulty: 'hard' },
  { word: 'résilience', type: 'definition', question: 'Que signifie "résilience" ?', options: ['Fragilité', 'Capacité à rebondir', 'Résistance passive', 'Faiblesse'], correctIndex: 1, difficulty: 'hard' },
  { word: 'flagornerie', type: 'definition', question: 'Que signifie "flagornerie" ?', options: ['Flatterie grossière', 'Critique sévère', 'Honnêteté brutale', 'Indifférence'], correctIndex: 0, difficulty: 'hard' },
  { word: 'inique', type: 'synonym', question: 'Synonyme de "inique"', options: ['Juste', 'Équitable', 'Injuste', 'Honnête'], correctIndex: 2, difficulty: 'hard' },
  { word: 'péremptoire', type: 'definition', question: 'Que signifie "péremptoire" ?', options: ['Hésitant', 'Timide', 'Nuancé', 'Qui n\'admet aucune discussion'], correctIndex: 3, difficulty: 'hard' },
  { word: 'abscond', type: 'definition', question: 'Que signifie "abscond" ?', options: ['Difficile à comprendre', 'Très clair', 'Simple', 'Évident'], correctIndex: 0, difficulty: 'hard' },
  { word: 'sycophante', type: 'definition', question: 'Que signifie "sycophante" ?', options: ['Philosophe', 'Délateur, calomniateur', 'Artiste', 'Bienfaiteur'], correctIndex: 1, difficulty: 'hard' },
  { word: 'insidieux', type: 'antonym', question: 'Antonyme de "insidieux"', options: ['Trompeur', 'Sournois', 'Franc', 'Perfide'], correctIndex: 2, difficulty: 'hard' },
  { word: 'magnanimité', type: 'synonym', question: 'Synonyme de "magnanimité"', options: ['Mesquinerie', 'Avarice', 'Rancune', 'Générosité d\'âme'], correctIndex: 3, difficulty: 'hard' },
  { word: 'fallacieux', type: 'synonym', question: 'Synonyme de "fallacieux"', options: ['Trompeur', 'Véridique', 'Sincère', 'Fiable'], correctIndex: 0, difficulty: 'hard' },
  { word: 'vindicatif', type: 'antonym', question: 'Antonyme de "vindicatif"', options: ['Rancunier', 'Clément', 'Vengeur', 'Hostile'], correctIndex: 1, difficulty: 'hard' },
  { word: 'immanent', type: 'antonym', question: 'Antonyme de "immanent"', options: ['Intérieur', 'Interne', 'Transcendant', 'Inhérent'], correctIndex: 2, difficulty: 'hard' },
  { word: 'anfractuosité', type: 'definition', question: 'Que signifie "anfractuosité" ?', options: ['Surface lisse', 'Ligne droite', 'Espace ouvert', 'Cavité irrégulière'], correctIndex: 3, difficulty: 'hard' },
  { word: 'léthargique', type: 'synonym', question: 'Synonyme de "léthargique"', options: ['Apathique', 'Énergique', 'Dynamique', 'Vif'], correctIndex: 0, difficulty: 'hard' },
  { word: 'specieux', type: 'definition', question: 'Que signifie "spécieux" ?', options: ['Authentique', 'Apparemment vrai mais faux', 'Remarquable', 'Ordinaire'], correctIndex: 1, difficulty: 'hard' },
  { word: 'récalcitrant', type: 'antonym', question: 'Antonyme de "récalcitrant"', options: ['Rebelle', 'Insoumis', 'Docile', 'Obstiné'], correctIndex: 2, difficulty: 'hard' },
  { word: 'ombrageux', type: 'definition', question: 'Que signifie "ombrageux" ?', options: ['Joyeux', 'Confiant', 'Sociable', 'Susceptible et méfiant'], correctIndex: 3, difficulty: 'hard' },
  { word: 'casuistique', type: 'definition', question: 'Que signifie "casuistique" ?', options: ['Étude des cas de conscience', 'Science des nombres', 'Art de la guerre', 'Étude des astres'], correctIndex: 0, difficulty: 'hard' },
  { word: 'cupide', type: 'synonym', question: 'Synonyme de "cupide"', options: ['Généreux', 'Avide', 'Modeste', 'Désintéressé'], correctIndex: 1, difficulty: 'hard' },

  // === EXPERT ===
  { word: 'ataraxie', type: 'definition', question: 'Que signifie "ataraxie" ?', options: ['Anxiété', 'Tranquillité absolue', 'Agitation', 'Mélancolie'], correctIndex: 1, difficulty: 'expert' },
  { word: 'syncrétisme', type: 'definition', question: 'Que signifie "syncrétisme" ?', options: ['Séparation', 'Fusion de doctrines', 'Opposition', 'Analyse'], correctIndex: 1, difficulty: 'expert' },
  { word: 'aporétique', type: 'definition', question: 'Que signifie "aporétique" ?', options: ['Qui résout', 'Sans issue logique', 'Qui simplifie', 'Qui éclaircit'], correctIndex: 1, difficulty: 'expert' },
  { word: 'épiphanie', type: 'definition', question: 'Que signifie "épiphanie" (sens figuré) ?', options: ['Disparition', 'Révélation soudaine', 'Oubli', 'Confusion'], correctIndex: 1, difficulty: 'expert' },
  { word: 'palimpseste', type: 'definition', question: 'Que signifie "palimpseste" ?', options: ['Texte original', 'Manuscrit réécrit', 'Livre neuf', 'Parchemin vierge'], correctIndex: 1, difficulty: 'expert' },
  { word: 'antinomique', type: 'synonym', question: 'Synonyme de "antinomique"', options: ['Compatible', 'Contradictoire', 'Similaire', 'Complémentaire'], correctIndex: 1, difficulty: 'expert' },
  { word: 'solipsisme', type: 'definition', question: 'Que signifie "solipsisme" ?', options: ['Foi en autrui', 'Seul le sujet existe', 'Amour universel', 'Confiance absolue'], correctIndex: 1, difficulty: 'expert' },
  { word: 'aporie', type: 'definition', question: 'Que signifie "aporie" ?', options: ['Solution', 'Impasse logique', 'Clarté', 'Réponse'], correctIndex: 1, difficulty: 'expert' },
  { word: 'sérendipité', type: 'definition', question: 'Que signifie "sérendipité" ?', options: ['Malchance', 'Découverte heureuse par hasard', 'Prévision', 'Planification'], correctIndex: 1, difficulty: 'expert' },
  { word: 'thuriféraire', type: 'definition', question: 'Que signifie "thuriféraire" ?', options: ['Critique', 'Flatteur excessif', 'Opposant', 'Juge'], correctIndex: 1, difficulty: 'expert' },
  { word: 'paroxysme', type: 'definition', question: 'Que signifie "paroxysme" ?', options: ['Point culminant d\'intensité', 'Début progressif', 'Déclin lent', 'État stable'], correctIndex: 0, difficulty: 'expert' },
  { word: 'axiologique', type: 'definition', question: 'Que signifie "axiologique" ?', options: ['Relatif à la logique', 'Relatif aux mathématiques', 'Relatif aux valeurs morales', 'Relatif au langage'], correctIndex: 2, difficulty: 'expert' },
  { word: 'ineffable', type: 'synonym', question: 'Synonyme de "ineffable"', options: ['Banal', 'Ordinaire', 'Commun', 'Indicible'], correctIndex: 3, difficulty: 'expert' },
  { word: 'dialectique', type: 'definition', question: 'Que signifie "dialectique" ?', options: ['Art de raisonner par opposition', 'Art de la persuasion', 'Art de la rhétorique', 'Art de l\'écriture'], correctIndex: 0, difficulty: 'expert' },
  { word: 'ubiquité', type: 'definition', question: 'Que signifie "ubiquité" ?', options: ['Absence totale', 'Présence partout à la fois', 'Rareté extrême', 'Isolement complet'], correctIndex: 1, difficulty: 'expert' },
  { word: 'tautologie', type: 'definition', question: 'Que signifie "tautologie" ?', options: ['Contradiction logique', 'Argument subtil', 'Répétition d\'une même idée', 'Raisonnement inductif'], correctIndex: 2, difficulty: 'expert' },
  { word: 'ontologique', type: 'definition', question: 'Que signifie "ontologique" ?', options: ['Relatif au langage', 'Relatif à la morale', 'Relatif à la beauté', 'Relatif à l\'être'], correctIndex: 3, difficulty: 'expert' },
  { word: 'contingent', type: 'antonym', question: 'Antonyme de "contingent"', options: ['Nécessaire', 'Aléatoire', 'Possible', 'Variable'], correctIndex: 0, difficulty: 'expert' },
  { word: 'herméneutique', type: 'definition', question: 'Que signifie "herméneutique" ?', options: ['Étude des nombres', 'Art de l\'interprétation des textes', 'Science de la nature', 'Théorie des formes'], correctIndex: 1, difficulty: 'expert' },
  { word: 'pléonasme', type: 'synonym', question: 'Synonyme de "pléonasme"', options: ['Contradiction', 'Euphémisme', 'Redondance', 'Litote'], correctIndex: 2, difficulty: 'expert' },
  { word: 'téléologique', type: 'definition', question: 'Que signifie "téléologique" ?', options: ['Relatif au hasard', 'Relatif au passé', 'Relatif aux origines', 'Relatif aux fins et aux buts'], correctIndex: 3, difficulty: 'expert' },
  { word: 'exégèse', type: 'definition', question: 'Que signifie "exégèse" ?', options: ['Interprétation approfondie d\'un texte', 'Résumé succinct', 'Traduction littérale', 'Critique superficielle'], correctIndex: 0, difficulty: 'expert' },
  { word: 'velléitaire', type: 'synonym', question: 'Synonyme de "velléitaire"', options: ['Déterminé', 'Irrésolu', 'Courageux', 'Audacieux'], correctIndex: 1, difficulty: 'expert' },
  { word: 'maïeutique', type: 'definition', question: 'Que signifie "maïeutique" ?', options: ['Art de la mémoire', 'Art de la dispute', 'Art d\'accoucher les esprits', 'Art de la persuasion'], correctIndex: 2, difficulty: 'expert' },
  { word: 'anfracteux', type: 'synonym', question: 'Synonyme de "anfracteux"', options: ['Lisse', 'Droit', 'Simple', 'Sinueux'], correctIndex: 3, difficulty: 'expert' },
  { word: 'eschatologie', type: 'definition', question: 'Que signifie "eschatologie" ?', options: ['Étude des fins dernières', 'Étude des origines', 'Étude des langues', 'Étude des sociétés'], correctIndex: 0, difficulty: 'expert' },
  { word: 'icastique', type: 'definition', question: 'Que signifie "icastique" ?', options: ['Abstrait', 'Qui représente fidèlement', 'Imaginaire', 'Déformé'], correctIndex: 1, difficulty: 'expert' },
  { word: 'immanence', type: 'antonym', question: 'Antonyme de "immanence"', options: ['Intériorité', 'Inhérence', 'Transcendance', 'Résidence'], correctIndex: 2, difficulty: 'expert' },
  { word: 'protéiforme', type: 'definition', question: 'Que signifie "protéiforme" ?', options: ['Rigide', 'Invariable', 'Uniforme', 'Qui change de forme'], correctIndex: 3, difficulty: 'expert' },

  // === MASTER ===
  { word: 'apophatique', type: 'definition', question: 'Que signifie "apophatique" ?', options: ['Qui affirme', 'Qui définit par la négation', 'Qui prouve', 'Qui catégorise'], correctIndex: 1, difficulty: 'master' },
  { word: 'épistémè', type: 'definition', question: 'Que signifie "épistémè" (Foucault) ?', options: ['Savoir individuel', 'Structure de pensée d\'une époque', 'Méthode scientifique', 'Théorie philosophique'], correctIndex: 1, difficulty: 'master' },
  { word: 'apodictique', type: 'definition', question: 'Que signifie "apodictique" ?', options: ['Incertain', 'Nécessairement vrai', 'Probablement faux', 'Discutable'], correctIndex: 1, difficulty: 'master' },
  { word: 'hypostasier', type: 'definition', question: 'Que signifie "hypostasier" ?', options: ['Simplifier', 'Transformer une abstraction en réalité', 'Détruire', 'Relativiser'], correctIndex: 1, difficulty: 'master' },
  { word: 'catachrèse', type: 'definition', question: 'Que signifie "catachrèse" ?', options: ['Répétition', 'Métaphore figée dans l\'usage', 'Exagération', 'Contradiction'], correctIndex: 1, difficulty: 'master' },
  { word: 'prétérition', type: 'definition', question: 'Que signifie "prétérition" ?', options: ['Dire en prétendant ne pas dire', 'Oublier volontairement', 'Exagérer un propos', 'Nier l\'évidence'], correctIndex: 0, difficulty: 'master' },
  { word: 'syllepse', type: 'definition', question: 'Que signifie "syllepse" ?', options: ['Double sens simultané', 'Accord incorrect', 'Phrase inversée', 'Mot inventé'], correctIndex: 0, difficulty: 'master' },
  { word: 'étiologie', type: 'definition', question: 'Que signifie "étiologie" ?', options: ['Étude des effets', 'Étude des causes', 'Étude des mots', 'Étude des formes'], correctIndex: 1, difficulty: 'master' },
  { word: 'propédeutique', type: 'definition', question: 'Que signifie "propédeutique" ?', options: ['Enseignement avancé', 'Enseignement préparatoire', 'Recherche fondamentale', 'Examen final'], correctIndex: 1, difficulty: 'master' },
  { word: 'heuristique', type: 'synonym', question: 'Synonyme de "heuristique"', options: ['Démonstratif', 'Exploratoire', 'Définitif', 'Restrictif'], correctIndex: 1, difficulty: 'master' },
  { word: 'idiosyncrasie', type: 'definition', question: 'Que signifie "idiosyncrasie" ?', options: ['Caractère commun', 'Tempérament propre à un individu', 'Maladie contagieuse', 'Habitude collective'], correctIndex: 1, difficulty: 'master' },
  { word: 'concupiscence', type: 'definition', question: 'Que signifie "concupiscence" ?', options: ['Sagesse', 'Désir ardent des biens terrestres', 'Indifférence', 'Piété'], correctIndex: 1, difficulty: 'master' },
  { word: 'stochastique', type: 'definition', question: 'Que signifie "stochastique" ?', options: ['Déterministe', 'Lié au hasard', 'Systématique', 'Prévisible'], correctIndex: 1, difficulty: 'master' },
  { word: 'anamnèse', type: 'definition', question: 'Que signifie "anamnèse" ?', options: ['Oubli total', 'Rappel à la mémoire', 'Perte de conscience', 'Confusion mentale'], correctIndex: 1, difficulty: 'master' },
  { word: 'paralogisme', type: 'definition', question: 'Que signifie "paralogisme" ?', options: ['Raisonnement valide', 'Raisonnement faux involontaire', 'Argument persuasif', 'Démonstration rigoureuse'], correctIndex: 1, difficulty: 'master' },
  { word: 'noumène', type: 'definition', question: 'Que signifie "noumène" (Kant) ?', options: ['Chose en soi, inaccessible aux sens', 'Apparence sensible', 'Idée abstraite', 'Phénomène observable'], correctIndex: 0, difficulty: 'master' },
  { word: 'épistémologie', type: 'definition', question: 'Que signifie "épistémologie" ?', options: ['Étude de la morale', 'Étude de la beauté', 'Étude de la connaissance', 'Étude du langage'], correctIndex: 2, difficulty: 'master' },
  { word: 'aséité', type: 'definition', question: 'Que signifie "aséité" ?', options: ['Dépendance totale', 'Existence sociale', 'Relation à autrui', 'Existence par soi-même'], correctIndex: 3, difficulty: 'master' },
  { word: 'antépénultième', type: 'definition', question: 'Que signifie "antépénultième" ?', options: ['Avant-avant-dernier', 'Tout premier', 'Dernier', 'Avant-dernier'], correctIndex: 0, difficulty: 'master' },
  { word: 'apothéose', type: 'synonym', question: 'Synonyme de "apothéose"', options: ['Déclin', 'Sommet glorieux', 'Échec', 'Médiocrité'], correctIndex: 1, difficulty: 'master' },
  { word: 'éristique', type: 'definition', question: 'Que signifie "éristique" ?', options: ['Art de la musique', 'Art de convaincre', 'Art de la controverse', 'Art de la contemplation'], correctIndex: 2, difficulty: 'master' },
  { word: 'synecdoque', type: 'definition', question: 'Que signifie "synecdoque" ?', options: ['Répétition de sons', 'Opposition de termes', 'Exagération rhétorique', 'La partie pour le tout'], correctIndex: 3, difficulty: 'master' },
  { word: 'phénoménologie', type: 'definition', question: 'Que signifie "phénoménologie" ?', options: ['Étude des apparitions à la conscience', 'Étude des phénomènes naturels', 'Étude des rêves', 'Étude des nombres'], correctIndex: 0, difficulty: 'master' },
  { word: 'prosopopée', type: 'definition', question: 'Que signifie "prosopopée" ?', options: ['Répétition insistante', 'Faire parler un absent ou une chose', 'Comparaison poétique', 'Inversion syntaxique'], correctIndex: 1, difficulty: 'master' },
  { word: 'solécisme', type: 'definition', question: 'Que signifie "solécisme" ?', options: ['Figure de style', 'Mot rare', 'Faute de syntaxe', 'Néologisme savant'], correctIndex: 2, difficulty: 'master' },
  { word: 'ipséité', type: 'definition', question: 'Que signifie "ipséité" ?', options: ['Altérité radicale', 'Perte de soi', 'Conscience collective', 'Ce qui fait qu\'on est soi-même'], correctIndex: 3, difficulty: 'master' },
  { word: 'enthymème', type: 'definition', question: 'Que signifie "enthymème" ?', options: ['Syllogisme abrégé', 'Contradiction logique', 'Argument circulaire', 'Preuve empirique'], correctIndex: 0, difficulty: 'master' },
  { word: 'pérégrination', type: 'synonym', question: 'Synonyme de "pérégrination"', options: ['Repos', 'Voyage lointain', 'Sommeil', 'Attente'], correctIndex: 1, difficulty: 'master' },
  { word: 'subsomption', type: 'definition', question: 'Que signifie "subsomption" ?', options: ['Division en parties', 'Généralisation abusive', 'Inclusion d\'un cas sous une règle', 'Exclusion d\'un concept'], correctIndex: 2, difficulty: 'master' },
];
